# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\createSlope_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateSlope_Dialog(object):
    def setupUi(self, CreateSlope_Dialog):
        CreateSlope_Dialog.setObjectName("CreateSlope_Dialog")
        CreateSlope_Dialog.resize(492, 123)
        CreateSlope_Dialog.setWhatsThis("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateSlope_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CreateSlope_Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.slopeName_lineEdit = QtWidgets.QLineEdit(CreateSlope_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slopeName_lineEdit.sizePolicy().hasHeightForWidth())
        self.slopeName_lineEdit.setSizePolicy(sizePolicy)
        self.slopeName_lineEdit.setMinimumSize(QtCore.QSize(250, 28))
        self.slopeName_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slopeName_lineEdit.setFont(font)
        self.slopeName_lineEdit.setStyleSheet("padding: 1px 3px 1px 3px;")
        self.slopeName_lineEdit.setObjectName("slopeName_lineEdit")
        self.horizontalLayout.addWidget(self.slopeName_lineEdit)
        self.pushButton = QtWidgets.QPushButton(CreateSlope_Dialog)
        self.pushButton.setMaximumSize(QtCore.QSize(33, 16777215))
        self.pushButton.setStyleSheet("background:rgba(0,0,0,0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(CreateSlope_Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.dir_label = QtWidgets.QLabel(CreateSlope_Dialog)
        self.dir_label.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dir_label.setFont(font)
        self.dir_label.setStyleSheet("background:rgb(255,255,255);\n"
"padding: 1px 3px 1px 3px;\n"
"align: right;\n"
"border: 0.5px solid rgb(210, 210, 210);")
        self.dir_label.setObjectName("dir_label")
        self.horizontalLayout_2.addWidget(self.dir_label)
        self.chooseDir_Button = QtWidgets.QPushButton(CreateSlope_Dialog)
        self.chooseDir_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\assets/openfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chooseDir_Button.setIcon(icon)
        self.chooseDir_Button.setObjectName("chooseDir_Button")
        self.horizontalLayout_2.addWidget(self.chooseDir_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.create_Button = QtWidgets.QPushButton(CreateSlope_Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.create_Button.setFont(font)
        self.create_Button.setObjectName("create_Button")
        self.horizontalLayout_3.addWidget(self.create_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CreateSlope_Dialog)
        QtCore.QMetaObject.connectSlotsByName(CreateSlope_Dialog)

    def retranslateUi(self, CreateSlope_Dialog):
        _translate = QtCore.QCoreApplication.translate
        CreateSlope_Dialog.setWindowTitle(_translate("CreateSlope_Dialog", "Create Slope"))
        self.label.setText(_translate("CreateSlope_Dialog", "Slope Name"))
        self.label_2.setText(_translate("CreateSlope_Dialog", "Save Directory"))
        self.dir_label.setText(_translate("CreateSlope_Dialog", " "))
        self.create_Button.setText(_translate("CreateSlope_Dialog", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateSlope_Dialog = QtWidgets.QDialog()
    ui = Ui_CreateSlope_Dialog()
    ui.setupUi(CreateSlope_Dialog)
    CreateSlope_Dialog.show()
    sys.exit(app.exec_())
